# リリース用プルリクエストを作成する
name: create-release-pr

on:
  push:
    branches:
      - dev
jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
#      https://github.com/x-motemen/git-pr-release を使用して Pull Request を作成する
      - name: Create a release pull request
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: main
          GIT_PR_RELEASE_BRANCH_STAGING: dev
          GIT_PR_RELEASE_TEMPLATE: .github/workflows/.git-pr-release-template
        run: |
          gem install -N git-pr-release
          git-pr-release
